import InDoor from "../assets/images/indoorCamera.png";
import OutDoor from "../assets/images/OutDoorCamera.png";
import Bell from "../assets/images/CameraOneShape.png";
import GarageControl from "../assets/images/GarageControl.webp";
import SmartLock from "../assets/images/SmartLock.webp";
import HomeControl from "../assets/images/HomeControl.webp";
import SafetyAlarm from "../assets/images/safteyAlarm.webp";




const products = [
    {
        id: 1,
        name: "Canon EOS 80D",
        category: "General Cameras",
        description: "Characterized by versatile imaging specs.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [929.99, 629.99],
        image: OutDoor,
        reviews: 50,
        rating: 4.5,
        features: ["High Resolution", "Motion Detection", "Audio Recording"],
    },
    {
        id: 2,
        name: "Nikon D750",
        category: "General Cameras",
        description: "High-quality DSLR for photography enthusiasts.",
        hasDiscount: false,
        inStock: false,
        wirless: false,
        price: [1699.99, 1699.99],
        image: OutDoor,
        reviews: 10,
        rating: 4.0,
        features: ["High Resolution", "Audio Recording"],
    },
    {
        id: 3,
        name: "Sony Alpha a7 III",
        category: "General Cameras",
        description: "Mirrorless camera with advanced features.",
        hasDiscount: false,
        inStock: true,
        wirless: false,
        price: [1999.99, 1999.99],
        image: OutDoor,
        reviews: 5,
        rating: 3.5,
        features: ["High Resolution", "Motion Detection", "Audio Recording"],
    },
    {
        id: 4,
        name: "Outdoor CCTV Camera",
        category: "CCTV Cameras",
        description: "Weather-resistant camera with night vision.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [149.99, 149.99],
        image: OutDoor,
        reviews: 45,
        rating: 4.5,
        features: ["Night Vision", "Motion Detection", "360° Angle View"],
    },
    {
        id: 5,
        name: "Indoor Dome Camera",
        category: "CCTV Cameras",
        description: "Discreet design for indoor surveillance.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [99.99, 79.99],
        image: InDoor,
        reviews: 30,
        rating: 4.0,
        features: ["Night Vision", "Motion Detection", "Audio Recording"],
    },
    {
        id: 6,
        name: "360-Degree Camera",
        category: "CCTV Cameras",
        description: "Provides full coverage with a rotating lens.",
        hasDiscount: false,
        inStock: false,
        wirless: true,
        price: [199.99, 199.99],
        image: InDoor,
        reviews: 15,
        rating: 4.2,
        features: ["Night Vision", "Motion Detection", "360° Angle View", "Audio Recording"],
    },
    {
        id: 7,
        name: "Motion Sensor",
        category: "Sensors",
        description: "Detects movement and triggers alerts.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [29.99, 19.99],
        image: Bell,
        reviews: 25,
        rating: 4.3,
        sensorDetection: "motion detection",
        features: ["Motion Detection"],
    },
    {
        id: 8,
        name: "Temperature Sensor",
        category: "Sensors",
        description: "Monitors ambient temperature changes.",
        hasDiscount: false,
        inStock: true,
        wirless: false,
        price: [19.99, 19.99],
        image: Bell,
        reviews: 20,
        rating: 4.0,
        sensorDetection: "temperature detection",
        features: [],
    },
    {
        id: 9,
        name: "Vibration Sensor",
        category: "Sensors",
        description: "Detects vibrations on doors and windows.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [14.99, 14.99],
        image: Bell,
        reviews: 12,
        rating: 3.9,
        sensorDetection: "motion detection",
        features: ["Motion Detection"],
    },
    {
        id: 10,
        name: "Smart Lock",
        category: "Smart Controls",
        description: "Secure and convenient locking system.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [129.99, 129.99],
        image: SmartLock,
        reviews: 40,
        rating: 4.5,
        features: ["Integration", "Audio Recording"],
    },
    {
        id: 11,
        name: "Home Control",
        category: "Smart Controls",
        description: "Automated control for your home.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [129.99, 129.99],
        image: HomeControl,
        reviews: 35,
        rating: 4.7,
        features: ["Integration", "Smart Control"],
    },
    {
        id: 12,
        name: "Garage Control",
        category: "Smart Controls",
        description: "Control your garage door remotely.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [79.99, 79.99],
        image: GarageControl,
        reviews: 25,
        rating: 4.0,
        features: ["Integration", "Smart Control"],
    },
    {
        id: 13,
        name: "Safety Alarm",
        category: "Alarms",
        description: "Detects smoke and alerts immediately.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [39.99, 29.99],
        image: SafetyAlarm,
        reviews: 50,
        rating: 4.8,
        features: ["Motion Detection", "Integration"],
    },
    {
        id: 14,
        category: 'Alarms',
        name: "Carbon Monoxide Alarm",
        description: "Ensures safety by detecting CO levels.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [49.99, 49.99],
        image: SafetyAlarm,
        reviews: 40,
        rating: 4.5,
        features: [
            "Motion Detection",
            "Integration"
        ]
    },
    {
        id: 15,
        category: 'Alarms',
        name: "Panic Alarm",
        description: "Emergency button to alert security systems.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [19.99, 14.99],
        image: SafetyAlarm,
        reviews: 15,
        rating: 4.1,
        features: [
            "Motion Detection",
            "Integration"
        ]
    },
    {
        id: 16,
        category: 'Bells',
        name: "Wireless Doorbell",
        description: "Stylish doorbell with long-range connectivity.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [39.99, 39.99],
        image: Bell,
        reviews: 25,
        rating: 4.3,
        features: [
            "Integration"
        ]
    },
    {
        id: 17,
        category: 'Bells',
        name: "Video Doorbell",
        description: "Integrated camera for monitoring visitors.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [149.99, 129.99],
        image: Bell,
        reviews: 40,
        rating: 4.6,
        features: [
            "Integration",
            "Motion Detection",
            "Audio Recording"
        ]
    },
    {
        id: 18,
        category: 'Bells',
        name: "Classic Chime Bell",
        description: "Traditional bell with a loud chime.",
        hasDiscount: false,
        inStock: false,
        wirless: false,
        price: [9.99, 9.99],
        image: Bell,
        reviews: 5,
        rating: 3.8,
        features: []
    }
];

export default products;

export const bestProducts = [
    {
        id: 5,
        name: "Indoor Dome Camera",
        category: "CCTV Cameras",
        description: "Discreet design for indoor surveillance.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [99.99, 79.99],
        image: InDoor,
        reviews: 30,
        rating: 4.0,
        features: ["Night Vision", "Motion Detection", "Audio Recording"],
    },
    {
        id: 1,
        name: "Canon EOS 80D",
        category: "General Cameras",
        description: "Characterized by versatile imaging specs.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [929.99, 629.99],
        image: OutDoor,
        reviews: 50,
        rating: 4.5,
        features: ["High Resolution", "Motion Detection", "Audio Recording"],
    },
    {
        id: 10,
        name: "Smart Lock",
        category: "Smart Controls",
        description: "Secure and convenient locking system.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [129.99, 129.99],
        image: SmartLock,
        reviews: 40,
        rating: 4.5,
        features: ["Integration", "Audio Recording"],
    },
    {
        id: 13,
        name: "Safety Alarm",
        category: "Alarms",
        description: "Detects smoke and alerts immediately.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [39.99, 29.99],
        image: SafetyAlarm,
        reviews: 50,
        rating: 4.8,
        features: ["Motion Detection", "Integration"],
    },
    {
        id: 12,
        name: "Garage Control",
        category: "Smart Controls",
        description: "Control your garage door remotely.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [79.99, 79.99],
        image: GarageControl,
        reviews: 25,
        rating: 4.0,
        features: ["Integration", "Smart Control"],
    },
    {
        id: 11,
        name: "Home Control",
        category: "Smart Controls",
        description: "Automated control for your home.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [129.99, 129.99],
        image: HomeControl,
        reviews: 35,
        rating: 4.7,
        features: ["Integration", "Smart Control"],
    },
    {
        id: 17,
        name: "Video Doorbell",
        category: "Bells",
        description: "Integrated camera for monitoring visitors.",
        hasDiscount: true,
        inStock: true,
        wirless: true,
        price: [149.99, 129.99],
        image: Bell,
        reviews: 40,
        rating: 4.6,
        features: ["Integration", "Motion Detection", "Audio Recording"],
    },
    {
        id: 4,
        name: "Outdoor CCTV Camera",
        category: "CCTV Cameras",
        description: "Weather-resistant camera with night vision.",
        hasDiscount: false,
        inStock: true,
        wirless: true,
        price: [149.99, 149.99],
        image: OutDoor,
        reviews: 45,
        rating: 4.5,
        features: ["Night Vision", "Motion Detection", "360° Angle View"],
    }
];



